#!/usr/bin/perl
use strict;
use warnings;
use opts;

use App::Donburi::Server;

opts my $conf => { isa => 'Str', default => 'config.yaml', comment => 'config file' };

App::Donburi::Server::run($conf);

