---
abstract: ~
author:
  - 'Kan Fushihara <kan dot fushihara at gmail dot com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Donburi
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  AnyEvent: 0
  AnyEvent::IRC::Client: 0
  Class::Accessor::Lite: 0
  Class::Load: 0
  Exporter: 5.36
  Plack::Request: 0
  Router::Simple: 0
  Scope::Container: 0
  String::CamelCase: 0
  Text::Xslate: 0
  Twiggy::Server: 0
  YAML: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
